### PR TITLE
upgrade maven-release-plugin to 3.0.0-M6

### PR DESCRIPTION
**Pull request by olamy**
- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Review by basil — APPROVED** [review]
Thanks for the PR!

**Comment by basil** [comment]
Causes [JENKINS-69198](https://issues.jenkins.io/browse/JENKINS-69198).

**Comment by jglick** [comment]
⇒ #296

**Comment by daniel-beck** [comment]
Caused (or contributed to) https://github.com/jenkins-infra/helpdesk/issues/3143

**Comment by basil** [comment]
https://github.com/jenkinsci/plugin-pom/pull/558 did not contain a description of the change, let alone its motivation or the reasoning behind it.

**Comment by olamy** [comment]
> [jenkinsci/plugin-pom#558](https://github.com/jenkinsci/plugin-pom/pull/558) did not contain a description of the change, let alone its motivation or the reasoning behind it.

motivation was this issue https://issues.apache.org/jira/browse/MRELEASE-1025 (some contributors had this issue).
Sorry if I didn't write that but I was trying to act as dependabot does (e.g no motivation) :)

Is there any issue logged in https://issues.apache.org/jira/projects/MRELEASE?
I can have a look when back from holidays.

**Comment by basil** [comment]
> "M" is milestone, right? Why are we using prerelease versions of dependencies?

Unclear to me, but both https://maven.apache.org/surefire/maven-surefire-plugin/ and https://maven.apache.org/maven-release/maven-release-plugin/ show "M" versions, and the last releases without an M were released in 2019 and 2015 respectively. Dependabot did not offer them specifically because they have an M and are considered prerelease, but if the Maven project considered them prereleases and was recommending a non-prerelease version for general usage, why would the web pages show the prerelease version, and why would the general usage version be so many years old? Does not make sense to me.

**Comment by jglick** [comment]
> some contributors had this issue

Contributors on Windows? They could switch to JEP-229 and never need to run MRP locally again, saving the lives of multiple kittens. :trollface:

**Pull request merged**
