### PR TITLE
Update localizer plugin

### PR DESCRIPTION
**Pull request by jtnord**
updates the localizer plugin to 1.28 (adds threadsagety support for parallel builds, and messages from XML)
https://github.com/kohsuke/localizer/compare/localizer-parent-1.26...localizer-parent-1.28

### CODE REVIEW

**Review by oleg-nenashev — APPROVED** [review]
They could have changed the groupId as well, right?

**Comment by jtnord** [comment]
> They could have changed the groupId as well, right?

they was me... but this has been setup to configured to allow pushing to maven central (but not actually done IIUC) so I did not want to make that change.

**Comment by jglick** [comment]
> this project has been setup to allow pushing to maven central (but not actually done IIUC)

Well, some versions, but not recent: https://search.maven.org/artifact/org.jvnet.localizer/maven-localizer-plugin

This is one of those projects we would really prefer to move into @jenkinsci if we could get @kohsuke on board.

**Comment by jtnord** [comment]
> Well, some versions, but not recent: https://search.maven.org/artifact/org.jvnet.localizer/maven-localizer-plugin

that was IIUC the old java.net publishing.  @kohsuke can push now via OSSRH https://issues.sonatype.org/browse/OSSRH-26780 / https://github.com/kohsuke/localizer/issues/7

**Comment by oleg-nenashev** [comment]
Let's get it release anyway. Thanks @jtnord !
+1 for moving to Jenkins or elsewhere

**Pull request merged**
