### PR TITLE
Update plugins

### PR DESCRIPTION
**Pull request by batmat**
Just made a pass of `versions:display-plugins-updates`. 

## Successful downstream PR builds with timestamped SNAPSHOT on the following components (`1.51-20181206.212314-4`):
* [x] Jenkins Core https://github.com/jenkinsci/jenkins/pull/3785 (PR failed, but on unrelated tests only)
* [x] Remoting https://github.com/jenkinsci/remoting/pull/310
* [x] Winstone https://github.com/jenkinsci/winstone/pull/59
* [x] Plugin Compat Tester https://github.com/jenkinsci/plugin-compat-tester/pull/91

Output was:

```
INFO] The following plugin updates are available:
[INFO]   io.jenkins.tools.incrementals:incrementals-maven-plugin  1.0-beta-5 -> 1.0-beta-7
[INFO]   maven-checkstyle-plugin ............................... 2.17 -> 3.0.0
[INFO]   maven-clean-plugin ................................... 3.0.0 -> 3.1.0
[INFO]   maven-dependency-plugin .............................. 3.0.2 -> 3.1.1
[INFO]   maven-deploy-plugin ............................... 2.8.2 -> 3.0.0-M1
[INFO]   maven-enforcer-plugin .......................... 3.0.0-M1 -> 3.0.0-M2
[INFO]   maven-help-plugin .................................... 3.0.1 -> 3.1.0
[INFO]   maven-idea-plugin ........................... 2.2 -> 2.3-atlassian-10
[INFO]   maven-install-plugin .............................. 2.5.2 -> 3.0.0-M1
[INFO]   maven-jar-plugin ..................................... 3.0.2 -> 3.1.0
[INFO]   maven-jxr-plugin ....................................... 2.5 -> 3.0.0
[INFO]   maven-pmd-plugin ...................................... 3.8 -> 3.11.0
[INFO]   maven-project-info-reports-plugin ...................... 2.9 -> 3.0.0
[INFO]   maven-remote-resources-plugin .......................... 1.5 -> 1.6.0
[INFO]   maven-resources-plugin ............................... 3.0.2 -> 3.1.0
[INFO]   maven-site-plugin ...................................... 3.7 -> 3.7.1
[INFO]   maven-surefire-plugin .............................. 2.20 -> 3.0.0-M1
[INFO]   maven-surefire-report-plugin ....................... 2.20 -> 3.0.0-M1
[INFO]   maven-war-plugin ..................................... 3.1.0 -> 3.2.2
[INFO]   org.codehaus.cargo:cargo-maven2-plugin ............... 1.1.2 -> 1.7.0
[INFO]   org.codehaus.mojo:gwt-maven-plugin ................. 2.3.0-1 -> 2.8.2
[INFO]   org.codehaus.mojo:versions-maven-plugin .................. 2.5 -> 2.7
[INFO]   org.codehaus.mojo:xml-maven-plugin ..................... 1.0 -> 1.0.2
[INFO]   org.jenkins-ci.tools:maven-hpi-plugin .................... 2.3 -> 2.7
[INFO]   org.jvnet.maven-antrun-extended-plugin:maven-antrun-extended-plugin  1.42 -> 1.43
[INFO]   org.mortbay.jetty:maven-jetty-plugin ........... 6.1.26 -> 7.0.0.pre5
```

### CODE REVIEW

**Comment by olamy** [comment]
do we really use idea or cargo or gwt plugins? We can probably get rid of those?

**Comment by jtnord** [comment]
the `deploy` plugin scares me a little bit and I think would be a blocker for the CERT team

https://issues.apache.org/jira/browse/MDEPLOY-244

**Comment by batmat** [comment]
Fine by me. This PR also definitely was intended to actually gather that feedback and still try to attempt as many components as we can. Going to revert `m-deploy-p` and Surefire related bumps and ask again for review. We'll reconsider these possibly later.

**Comment by batmat** [comment]
@oleg-nenashev @jtnord I reverted `m-surefire-*-p` and `m-deploy-p`. Care to re-review?

Also pushed a new timestamped SNAPSHOT `1.51-20181203.164412-3` into https://github.com/jenkinsci/jenkins/pull/3785 to test its behavior.

Thanks

**Comment by batmat** [comment]
All upstream PRs filed @oleg-nenashev. We'll see how they go.

**Comment by batmat** [comment]
All downstream PRs successful. Merging given the review approvals.

**Pull request merged**
