### PR TITLE
Add findsecbugs plugin to spotbugs

### PR DESCRIPTION
**Pull request by StefanSpieker**
I added [find-sec-bugs ](https://github.com/find-sec-bugs/find-sec-bugs) plugin to spotbugs. I don't think that it should be merged right away, because there are a lot of findigs in Jenkins. This is here for discussion, if this is useful at all.

But I found for example:
https://github.com/jenkinsci/jenkins/pull/4363

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
@Wadeck @jeffret-b Do we want to enable it in all components? I see you submitted your PRs in Core and Remoting, so your feedback would be very useful

**Comment by jeffret-b** [comment]
I would like to get this change merged. I'm working to propose the equivalent for the plugin-pom. 

The big question I see is how we get there. I'm going to start a discussion on the dev mailing list, to try and solicit input on how we proceed.

**Comment by jeffret-b** [comment]
I sent a message to the Jenkins Dev list to start getting feedback about turning on findsecbugs in the Jenkins developer ecosystem. See https://groups.google.com/forum/#!topic/jenkinsci-dev/exd3fc9NUAg

I think we should accept this PR and make findsecbugs a standard part of the build process for components using this parent pom. Developers updating these components will need to fix or suppress any findings when updating the pom before the next release.

When we merge this, we should remove the pieces about findsecbugs I'm currently adding directly into the Jenkins and Remoting poms.

(I'm not so sure about the equivalent change for the plugin parent pom. Does making it the default become too burdensome?)

**Comment by oleg-nenashev** [comment]
This is still blocked by the dev list discussion, right?

**Comment by jeffret-b** [comment]
There isn't really anything blocking in the dev list discussion. But, I don't think we want to proceed here until after we've got agreement to proceed on jenkinsci/#4381. We seem to be getting close there. I'd like to get @Wadeck to comment there again but James seems to be okay with where it's going.

Anybody have any idea what different projects would be impacted by this pom change?

**Comment by oleg-nenashev** [comment]
> Anybody have any idea what different projects would be impacted by this pom change?

Well, there are dozens of repos depending on this POM. some of them will be likely full by false-positives. Personally I would be fine with merging if there was a way to opt-out from FindSecBugs via a Maven property

**Comment by jeffret-b** [comment]
I've been wondering about whether to pursue opt-in or opt-out. Given your comment, I propose this PR be adapted to have an opt-out via a maven property and then we proceed with merging it. I would merge after we get jenkinsci/jenkins#4381 in then I'll back out the pom modifications there.

**Comment by oleg-nenashev** [comment]
opt-out is fine with me

**Comment by jeffret-b** [comment]
I agree that we should get this moving forward and that we need a clear way of opting out.

**Comment by jeffret-b** [comment]
There's already an easy way of opting out. Just add this to a spotbugs excludes file, which is already well-supported in our environment:
```
<FindBugsFilter>
    <Match>
        <Bug category="SECURITY"/>
    </Match>
</FindBugsFilter>
```

What we're going to need is more communication, so that people understand what is going on, how to handle the findings, and how to opt out like this. 

I've had a few more examples of adding this to plugins sitting around. I've been waiting around to make sure we can get some movement in Jenkins before pushing on those areas. I'll work on getting those proposed.

After I've got those up as some examples, I'd be happy to submit additional comments on the email lists, blog posts, or even some demos. Whatever would be helpful for getting the word out. Once we can disseminate that information, we should go ahead with this PR and see about an equivalent one in the plugin parent pom.

**Comment by MarkEWaite** [comment]
I consistently encounter https://github.com/spotbugs/spotbugs/issues/527 when I attempt to enable findsecbugs on the platformlabeler-plugin.  That bug makes it impossible to enable findsecbugs on platformlabeler-plugin.

So long as there is a clear way to opt out and the opt out technique will avoid https://github.com/spotbugs/spotbugs/issues/527, then I'm fine with the change.

I fear that the "opt out" to avoid that bug will likely require that I insert the spotbugs plugin definition into the pom and then declare a configuration which does not include findsecbugs.

**Comment by jeffret-b** [comment]
@MarkEWaite, I don't see spotbugs issue 527 as being a significant problem. Sure it adds a few unnecessary lines to the build log, but it doesn't cause any real issues. As the maintainers mention there, they should "make sure we don't raise stupid warnings" but the stupid warnings don't really cause problems.

Take a look at  jenkinsci/platformlabeler-plugin#165 for an example of how the plugin would behave. Of particular note, is that findsecbugs doesn't find anything in platformlabeler, but could potentially help avoid things that might creep in sometime in the future. That PR also demonstrates opting-out of some or all checks related to findsecbugs.

**Comment by MarkEWaite** [comment]
I don't intend to block this change.  If others feel it will help the project and the community, I'm willing to adapt my use to it.

**Comment by jeffret-b** [comment]
It's time to get this one moving forward. The change looks fine. I've double-checked it locally and seen that it does what we want.

I have provided information about my experiences and observations, including recommendations for developers on the Jenkins blog [Findsecbugs for Developers](https://jenkins.io/blog/2020/03/02/findsecbugs/) and Jenkins Online Meetup [2020 03 11 Developer Meetup find sec bugs for core and plugins](https://youtu.be/fotttu20Mf4).

Opt-out is the best way to go, for two reasons, 1) we really want people to adopt findsecbugs, and 2) given the way maven configuration works, opt-out is much simpler. I describe how to do it in the resources referenced above.

**Comment by jtnord** [comment]
where's the opt out option.  

having to create a spotbugs exclusion or adding annotations is not viable when maintaining many plugins, and these exclusions typiciall don't work well in a multi module setup where more work is required.

I have only seen the Jenkins core Of that was more false positives than anything else, maybe I missed some PRs to plugins where this was enabled.

**Comment by jeffret-b** [comment]
There have been no new comments on this since I raised it in the dev list again and mentioned here that it looks ready to go. I will add a ready-to-merge label. After a day or so delay for any further comments we will be ready to go on this. Then we can see if we can get this merged and released.

**Comment by jeffret-b** [comment]
Let's try getting a build again.

**Comment by jeffret-b** [comment]
I consider this good to go at this point, @oleg-nenashev.

Maven and spotbugs really don't support opt-in well. About the only way to do opt-in is to not integrate this change at the parent pom level and recommend that anyone who wants to opt-in  applies the comparable change to this one in their own project pom. That leads to very little adoption of this tool. Other opt-in mechanisms would be very convoluted.

On the other hand, the opt-out is very simple -- just add `<Bug category="SECURITY"/>` to the exclusion file.

**Comment by timja** [comment]
Looks like oleg's concern has been addressed,

> Even if we enable it by default, I kindly ask for a documented way to opt-out

**Comment by timja** [comment]
This has been ready-for-merge for 2 weeks, has 5 approvals and no further feedback in the mailing list,

🚢

**Pull request merged**
