### PR TITLE
Rename old changelog - prevent GitHub UI showing to users

### PR DESCRIPTION
**Pull request by timja**
GitHub is showing a link to the changelog on the releases page: https://github.com/jenkinsci/pom/releases

We don't want that

### CODE REVIEW

**Review by Vlatombe — APPROVED** [review]

**Comment by jglick** [comment]
I guess this will be needed in a lot of cases. Actually I would suggest just _deleting_ the old changelog file, then changing the link from `README.md` to be a permalink to the last state before it was deleted—presumably there will never be a need to edit it going forward, right?

**Comment by jglick** [comment]
BTW where do you see this? https://github.com/jenkinsci/workflow-job-plugin/releases does not show anything amiss that I can see despite https://github.com/jenkinsci/workflow-job-plugin/blob/master/CHANGELOG.md

**Comment by timja** [comment]
image

**Comment by jglick** [comment]
I do not see that either anonymously or when logged in. Some browser customization or beta program?
unauthenticated
authenticated

**Comment by timja** [comment]
ah must be refined github (https://github.com/sindresorhus/refined-github)

**Comment by daniel-beck** [comment]
So this can be reverted?

**Comment by timja** [comment]
> So this can be reverted?

no point? It could be moved to a link in the readme

**Pull request merged**
